### ISSUE TITLE
Unnecessary Wiki

### ISSUE THREAD

**Issue by vandench** [Team-2502/RobotCode2016#4]
Disable the wiki in this repos settings, it is not needed and won't be used.

**Comment by BinEP** [comment]
We might want this for programming guides. Like the basics for the robot. Do you want to do that at all? Get the basics down? Or should I?

**Comment by vandench** [comment]
If we do want to do this I can work on the wiki, but most of the important bits are on http://wpilib.screenstepslive.com/s/4485

**Comment by BinEP** [comment]
True, but it would be good to get the things into 1 place and keep it to the things we use, rather than everything. Plus we only use certain ones.
